events {
    worker_connections 1024;
}

http {
    upstream website {
        server website:3000;  
    }

    upstream umami {
        server umami:3000;
    }

    server {
        listen 80;
        server_name peter-griffer.online peter-griffer.ru;

        
        location /_next/static/ {
            proxy_pass http://website/_next/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            expires 1y;
            add_header Cache-Control "public, immutable";
        }

        
        location /static/ {
            proxy_pass http://website/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            expires 1y;
            add_header Cache-Control "public";
        }

        
        location ~* \.(ico|png|jpg|jpeg|gif|svg|webmanifest|css|js)$ {
            proxy_pass http://website;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            expires 1y;
            add_header Cache-Control "public";
        }

       
        location / {
            proxy_pass http://website;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
        
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_cache_bypass $http_upgrade;
        }

       
        location /analytics/ {
            proxy_pass http://umami;  
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_cache_bypass $http_upgrade;
            
            
            rewrite ^/analytics/(.*)$ /$1 break;
        }
    }
}