name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install npm
        run: npm install
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npm run test:lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install npm
        run: npm install
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm run test
  build:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install npm
        run: npm install
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build:image
      - name: Docker Compose Up
        run: npm run docker:compose
      - name: Test with Curl
        run: npm run test:curl